version: '3'
services:
  # New relic agent
  agent:
    container_name: newrelic-infra-teleport
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    restart: unless-stopped

  # Telos (native) mainnet
  teleport-reporter1-telos:
    command: "node reporter-eos.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter1-telos
    volumes:
      - ./oracle/config/tevm-config1.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter1-telos
    env_file:
      - .env
  teleport-reporter2-telos:
    command: "node reporter-eos.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter2-telos
    volumes:
      - ./oracle/config/tevm-config2.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter2-telos
    env_file:
      - .env
  teleport-reporter3-telos:
    command: "node reporter-eos.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter3-telos
    volumes:
      - ./oracle/config/tevm-config3.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter3-telos
    env_file:
      - .env

  # Ethereum mainnet
  teleport-reporter1-eth:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter1-eth
    volumes:
      - ./oracle/config/eth-config1.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter1-eth
    env_file:
      - .env
  teleport-reporter2-eth:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter2-eth
    volumes:
      - ./oracle/config/eth-config2.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter2-eth
    env_file:
      - .env
  teleport-reporter3-eth:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter3-eth
    volumes:
      - ./oracle/config/eth-config3.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter3-eth
    env_file:
      - .env

  # BSC mainnet
  teleport-reporter1-bsc:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter1-bsc
    volumes:
      - ./oracle/config/bsc-config1.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter1-bsc
    env_file:
      - .env
  teleport-reporter2-bsc:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter2-bsc
    volumes:
      - ./oracle/config/bsc-config2.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter2-bsc
    env_file:
      - .env
  teleport-reporter3-bsc:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter3-bsc
    volumes:
      - ./oracle/config/bsc-config3.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter3-bsc
    env_file:
      - .env

  # Telos evm mainnet
  teleport-reporter1-tevm:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter1-tevm
    volumes:
      - ./oracle/config/tevm-config1.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter1-tevm
    env_file:
      - .env
  teleport-reporter2-tevm:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter2-tevm
    volumes:
      - ./oracle/config/tevm-config2.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter2-tevm
    env_file:
      - .env
  teleport-reporter3-tevm:
    command: "node reporter-eth.js"
    restart: always
    build:
      context: .
    image: "teleport-reporter:v2"
    container_name: teleport-reporter3-tevm
    volumes:
      - ./oracle/config/tevm-config3.js:/home/node/app/reporter/config.js
    environment:
      - NEW_RELIC_APP_NAME=teleport-reporter3-tevm
    env_file:
      - .env